# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from saebooks_desktop.grpc_gen import saebooks_pb2 as saebooks__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in saebooks_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SAEBooksStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListContacts = channel.unary_unary(
                '/saebooks.SAEBooks/ListContacts',
                request_serializer=saebooks__pb2.ListContactsRequest.SerializeToString,
                response_deserializer=saebooks__pb2.ListContactsResponse.FromString,
                _registered_method=True)
        self.GetContact = channel.unary_unary(
                '/saebooks.SAEBooks/GetContact',
                request_serializer=saebooks__pb2.GetContactRequest.SerializeToString,
                response_deserializer=saebooks__pb2.ContactResponse.FromString,
                _registered_method=True)
        self.CreateContact = channel.unary_unary(
                '/saebooks.SAEBooks/CreateContact',
                request_serializer=saebooks__pb2.CreateContactRequest.SerializeToString,
                response_deserializer=saebooks__pb2.ContactResponse.FromString,
                _registered_method=True)
        self.UpdateContact = channel.unary_unary(
                '/saebooks.SAEBooks/UpdateContact',
                request_serializer=saebooks__pb2.UpdateContactRequest.SerializeToString,
                response_deserializer=saebooks__pb2.ContactResponse.FromString,
                _registered_method=True)
        self.ArchiveContact = channel.unary_unary(
                '/saebooks.SAEBooks/ArchiveContact',
                request_serializer=saebooks__pb2.ArchiveContactRequest.SerializeToString,
                response_deserializer=saebooks__pb2.ContactResponse.FromString,
                _registered_method=True)
        self.WatchChanges = channel.unary_stream(
                '/saebooks.SAEBooks/WatchChanges',
                request_serializer=saebooks__pb2.WatchChangesRequest.SerializeToString,
                response_deserializer=saebooks__pb2.ChangeEvent.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/saebooks.SAEBooks/Heartbeat',
                request_serializer=saebooks__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=saebooks__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class SAEBooksServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListContacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchiveContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchChanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SAEBooksServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListContacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContacts,
                    request_deserializer=saebooks__pb2.ListContactsRequest.FromString,
                    response_serializer=saebooks__pb2.ListContactsResponse.SerializeToString,
            ),
            'GetContact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContact,
                    request_deserializer=saebooks__pb2.GetContactRequest.FromString,
                    response_serializer=saebooks__pb2.ContactResponse.SerializeToString,
            ),
            'CreateContact': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateContact,
                    request_deserializer=saebooks__pb2.CreateContactRequest.FromString,
                    response_serializer=saebooks__pb2.ContactResponse.SerializeToString,
            ),
            'UpdateContact': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateContact,
                    request_deserializer=saebooks__pb2.UpdateContactRequest.FromString,
                    response_serializer=saebooks__pb2.ContactResponse.SerializeToString,
            ),
            'ArchiveContact': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveContact,
                    request_deserializer=saebooks__pb2.ArchiveContactRequest.FromString,
                    response_serializer=saebooks__pb2.ContactResponse.SerializeToString,
            ),
            'WatchChanges': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchChanges,
                    request_deserializer=saebooks__pb2.WatchChangesRequest.FromString,
                    response_serializer=saebooks__pb2.ChangeEvent.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=saebooks__pb2.HeartbeatRequest.FromString,
                    response_serializer=saebooks__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'saebooks.SAEBooks', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('saebooks.SAEBooks', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SAEBooks(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListContacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saebooks.SAEBooks/ListContacts',
            saebooks__pb2.ListContactsRequest.SerializeToString,
            saebooks__pb2.ListContactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saebooks.SAEBooks/GetContact',
            saebooks__pb2.GetContactRequest.SerializeToString,
            saebooks__pb2.ContactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saebooks.SAEBooks/CreateContact',
            saebooks__pb2.CreateContactRequest.SerializeToString,
            saebooks__pb2.ContactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saebooks.SAEBooks/UpdateContact',
            saebooks__pb2.UpdateContactRequest.SerializeToString,
            saebooks__pb2.ContactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArchiveContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saebooks.SAEBooks/ArchiveContact',
            saebooks__pb2.ArchiveContactRequest.SerializeToString,
            saebooks__pb2.ContactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/saebooks.SAEBooks/WatchChanges',
            saebooks__pb2.WatchChangesRequest.SerializeToString,
            saebooks__pb2.ChangeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saebooks.SAEBooks/Heartbeat',
            saebooks__pb2.HeartbeatRequest.SerializeToString,
            saebooks__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
